
name = "boae-v1"
#main = worker/src/index.ts
compatibility_date = "2025-11-29"

# Pages project configuration
[site]
bucket = "./boae-v1/blink-of-an-eye/frontend"        # Static assets directory
entry-point = "functions"    # Pages Functions directory

# Optional: environment variables
[vars]
YOUTUBE_CHANNEL_ID = "UCwaM48qdZeWsII30OCMnShg"
[vars]
YOUTUBE_API_KEY = "AIzaSyD8by2ePwkkXzkqtJefXSSdmSD34WrMj2"

# Secrets are added via wrangler CLI
# wrangler secret put YOUTUBE_API_KEY
# wrangler secret put INSTAGRAM_ACCESS_TOKEN
