name = "boae-v1-worker"
main = "worker/src/index.ts"
compatibility_date = "2025-11-29"
[vars]
YOUTUBE_CHANNEL_ID = "UCwaM48qdZeWsII30OCMnShg"
YOUTUBE_API_KEY = "AIzaSyD8by2ePwkkXzkqtJefXSSdmSD34WrMj2"