name = "boae-v1-worker"
main = "worker/src/index.ts"
compatibility_date = "2025-11-29"
[vars]
YOUTUBE_CHANNEL_ID = "UCwaM48qdZeWsII30OCMnShg"
YOUTUBE_API_KEY = "AIzaSyD8by2ePwkkXzkqtJefXSSdmSD34WrMj2"
CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_BOAE}}
CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}